server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
#  security:
#    user:
#      name: test
#      password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 586342851147-u882i7lqh5g1ff3dop4c6k1ibi3ma8i3.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: QCQgMJv4K_WqygnocSU_
            client-secret: EcOBpqjgBs
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web1.cn7f8p35wkwj.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
        
  
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/sdw/sdw/workspace/security_donguk/security_donguk/upload/  

